### ISSUE TITLE
Stretch background image

### ISSUE THREAD

**Issue by SparklesReal** [simrail/EDR#96]
The current background on the website just repeats instead of stretching in 2560x1440 resolution

![image](https://github.com/simrail/EDR/assets/68858896/3ca14f16-9b6b-4dcc-bbc4-7a2d8c6e68ff)

**Comment by chill0r** [comment]
The background was changed from `cover` to `auto` in the commit https://github.com/simrail/EDR/commit/313731963c603ac7bb6d388f78682894e4fc4246
I don't know what the reason was to change it because `cover` scales the image (while preserving its ratio) to the smallest possible size to fill [^1].

When changed back to `cover` (tested using the developer tools in both Chrome and Firefox) the background image scales with the window size and looks quite fine.

Example 1 (3777x1914):
![image](https://github.com/simrail/EDR/assets/1339474/aa3fbd2f-58c7-4d13-a011-9fd32437a9f8)

Example 2 (795x902):
![image](https://github.com/simrail/EDR/assets/1339474/14c92811-3d66-4cd1-8417-4a5884dd506b)

Example 3 (576x297):
![image](https://github.com/simrail/EDR/assets/1339474/ddc8354d-8ec4-4312-b453-2bcf888e9217)


[^1]: https://developer.mozilla.org/en-US/docs/Web/CSS/background-size

**Comment by Tallyrald** [comment]
You guys are absolutely correct, thanks!
